// NRFusion v0.5.4 - Matched Residual & Downsample Compute Shaders
// Zero-CPU GPU-only pipeline for Synthetic DLAA and low-resolution Neural Rendering.

#define THREAD_GROUP_X 16
#define THREAD_GROUP_Y 16

cbuffer DownsampleCB : register(b0) {
    uint g_srcWidth;
    uint g_srcHeight;
    uint g_dstWidth;
    uint g_dstHeight;
};

Texture2D<float4>   g_srcTexture : register(t0);
RWTexture2D<float4> g_dstTexture : register(u0);

[numthreads(THREAD_GROUP_X, THREAD_GROUP_Y, 1)]
void CSDownsample(uint3 id : SV_DispatchThreadID) {
    if (id.x >= g_dstWidth || id.y >= g_dstHeight) return;

    float2 uv = (float2(id.xy) + 0.5f) / float2(g_dstWidth, g_dstHeight);
    float2 srcCoord = uv * float2(g_srcWidth, g_srcHeight) - 0.5f;

    // Bilinear box filter across source footprint
    float xd = clamp(srcCoord.x, 0.0f, float(g_srcWidth - 1));
    float yd = clamp(srcCoord.y, 0.0f, float(g_srcHeight - 1));
    uint x0 = uint(floor(xd));
    uint y0 = uint(floor(yd));
    uint x1 = min(x0 + 1, g_srcWidth - 1);
    uint y1 = min(y0 + 1, g_srcHeight - 1);
    float fx = xd - float(x0);
    float fy = yd - float(y0);

    float4 s00 = g_srcTexture.Load(int3(x0, y0, 0));
    float4 s10 = g_srcTexture.Load(int3(x1, y0, 0));
    float4 s01 = g_srcTexture.Load(int3(x0, y1, 0));
    float4 s11 = g_srcTexture.Load(int3(x1, y1, 0));

    float4 interpolated = lerp(lerp(s00, s10, fx), lerp(s01, s11, fx), fy);
    g_dstTexture[id.xy] = interpolated;
}

cbuffer ResidualExtractCB : register(b0) {
    uint g_workWidth;
    uint g_workHeight;
    float g_preExposure;
    float g_padding;
};

Texture2D<float4>   g_neuralOutput : register(t0);
Texture2D<float4>   g_neuralInput  : register(t1);
RWTexture2D<float4> g_lowResidual  : register(u0);

[numthreads(THREAD_GROUP_X, THREAD_GROUP_Y, 1)]
void CSExtractResidual(uint3 id : SV_DispatchThreadID) {
    if (id.x >= g_workWidth || id.y >= g_workHeight) return;

    int3 coord = int3(id.xy, 0);
    float4 nOut = g_neuralOutput.Load(coord);
    float4 nIn  = g_neuralInput.Load(coord);

    // Filter NaNs/Infs
    if (any(isnan(nOut)) || any(isinf(nOut))) nOut = 0.0f;
    if (any(isnan(nIn))  || any(isinf(nIn)))  nIn  = 0.0f;

    // Residual in low-res space: Difference generated by neural passes
    float4 residual = nOut - nIn;
    g_lowResidual[id.xy] = residual;
}

cbuffer ResidualComposeCB : register(b0) {
    uint g_nativeWidth;
    uint g_nativeHeight;
    uint g_residualWidth;
    uint g_residualHeight;
    float g_residualWeight;
    float g_composeExposure;
    float g_padding0;
    float g_padding1;
};

Texture2D<float4>   g_originalNative : register(t0);
Texture2D<float4>   g_residualSource : register(t1);
RWTexture2D<float4> g_composedNative : register(u0);

[numthreads(THREAD_GROUP_X, THREAD_GROUP_Y, 1)]
void CSComposeResidual(uint3 id : SV_DispatchThreadID) {
    if (id.x >= g_nativeWidth || id.y >= g_nativeHeight) return;

    int3 nativeCoord = int3(id.xy, 0);
    float4 orig = g_originalNative.Load(nativeCoord);
    if (any(isnan(orig)) || any(isinf(orig))) orig = 0.0f;

    // Bilinear sample of the low-resolution residual
    float2 uv = (float2(id.xy) + 0.5f) / float2(g_nativeWidth, g_nativeHeight);
    float2 resCoord = uv * float2(g_residualWidth, g_residualHeight) - 0.5f;

    float rx = clamp(resCoord.x, 0.0f, float(g_residualWidth - 1));
    float ry = clamp(resCoord.y, 0.0f, float(g_residualHeight - 1));
    uint rx0 = uint(floor(rx));
    uint ry0 = uint(floor(ry));
    uint rx1 = min(rx0 + 1, g_residualWidth - 1);
    uint ry1 = min(ry0 + 1, g_residualHeight - 1);
    float rfx = rx - float(rx0);
    float rfy = ry - float(ry0);

    float4 r00 = g_residualSource.Load(int3(rx0, ry0, 0));
    float4 r10 = g_residualSource.Load(int3(rx1, ry0, 0));
    float4 r01 = g_residualSource.Load(int3(rx0, ry1, 0));
    float4 r11 = g_residualSource.Load(int3(rx1, ry1, 0));

    float4 res = lerp(lerp(r00, r10, rfx), lerp(r01, r11, rfx), rfy);
    if (any(isnan(res)) || any(isinf(res))) res = 0.0f;

    // NativeResult = OriginalNative + (UpscaledResidual * weight)
    float4 finalResult = orig + (res * g_residualWeight);
    g_composedNative[id.xy] = finalResult;
}
